### ISSUE TITLE
Implementation of BYE seems to violate Assuan spec

### ISSUE THREAD

**Issue by jbrubake** [phenax/any-pinentry#7]
4f5ed2a from #5 changed the `BYE` command so that it no longer prints a message. From my reading of the [Assuan spec](https://www.gnupg.org/%28en%29/documentation/manuals/assuan.pdf) (see the bottom of page 7), the `BYE` command should print `OK`.

@jspricke what error were you fixing with this?

**Comment by jspricke** [comment]
From what I remember it fixed exactly what is written in the commit message, i.e.:
```
bin/anypinentry: 165: printf: printf: I/O error
```

**Comment by jbrubake** [comment]
(I could have worded my question better.)

What were the circumstances that *caused* that error? If revert the commit and then run `pinentry-any` and manually give it the `BYE` command, it properly prints the string with no error.

I'm curious if the way in which `pinentry-any` was called (i.e., from another program) was causing the error? The error message mentioning `printf` is also interesting when `echo` was the command.

**Comment by jspricke** [comment]
I have a standard Debian unstable with X11 and the `gpg-agent` is started by `/etc/X11/Xsession.d/90gpg-agent` so error messages are in the `journald`. Reverting 4f5ed2a gives me this in the log:
```
Okt 04 18:28:33 fenchel gpg-agent[156745]: bin/anypinentry: 162: echo: echo: I/O error
```
No idea where the `printf` is coming from.

**Comment by phenax** [comment]
`gpg-agent` must be closing the stdio right after sending BYE. I think if the spec expects the `OK` it makes sense to send it anyway. We can just `|| true 2>/dev/null` it or something to keep things sane. What do you all think?

**Comment by jspricke** [comment]
@phenax still produces the same error for me.

**Comment by jbrubake** [comment]
> `gpg-agent` must be closing the stdio right after sending BYE. I think if the spec expects the `OK` it makes sense to send it anyway. We can just `|| true 2>/dev/null` it or something to keep things sane. What do you all think?

I think `anypinentry` should follow the spec.

`gpg-agent` is generating the error so adding `|| true` wouldn't have any effect. If things work correctly (minus the I/O error) my guess would be that `gpg-agent` is doing something odd/unexpected, not that `anypinentry` has a problem.

**Comment by jspricke** [comment]
I agree and opened #8 to fix this. My best guess is that other pinentry implementations don't show this error because they are not run by a shell, at least I also see a broken pipe when stracing them.

**Comment by jbrubake** [comment]
I know I'm being pedantic, but per the spec, the server should reply with "OK" only

**Comment by phenax** [comment]
> I know I'm being pedantic, but per the spec, the server should reply with "OK" only

@jbrubake, All of the pinentry programs I've tested reply with `OK closing connection` for `BYE`.

**Comment by jbrubake** [comment]
I'm just going off GNU's documentation. I don't think 'OK closing connection' will break anything.
